# Generated by Django 4.2.1 on 2023-05-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='content',
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
