# Generated by Django 4.2.1 on 2023-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0002_rename_date_guestbook_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
